# permissions for end users to edit dnsrecords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dnshealthcheckprobe-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dns-operator
    app.kubernetes.io/part-of: dns-operator
    app.kubernetes.io/managed-by: kustomize
  name: dnshealthcheckprobe-editor-role
rules:
- apiGroups:
  - kuadrant.io
  resources:
  - dnshealthcheckprobes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - dnshealthcheckprobes/status
  verbs:
  - get
